# Generated by Django 5.0.2 on 2024-02-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description3',
        ),
    ]
