# Generated by Django 5.0.3 on 2024-04-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_order_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
